#theme: minima
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: RecHumS - Reconstructing the Human Skeleton
description: A website for the quick navigation of the dissemination actions and the developed software of the "RecHumS" project, funded by the H.F.R.I..
